-- AlterTable: User
ALTER TABLE "users" ALTER COLUMN "email" SET DATA TYPE VARCHAR(254);
ALTER TABLE "users" ALTER COLUMN "badgeCode" SET DATA TYPE VARCHAR(20);
ALTER TABLE "users" ALTER COLUMN "firstName" SET DATA TYPE VARCHAR(100);
ALTER TABLE "users" ALTER COLUMN "lastName" SET DATA TYPE VARCHAR(100);
ALTER TABLE "users" ALTER COLUMN "phone" SET DATA TYPE VARCHAR(20);

-- AlterTable: Station
ALTER TABLE "stations" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100);
ALTER TABLE "stations" ALTER COLUMN "address" SET DATA TYPE VARCHAR(255);
ALTER TABLE "stations" ALTER COLUMN "city" SET DATA TYPE VARCHAR(100);
ALTER TABLE "stations" ALTER COLUMN "phone" SET DATA TYPE VARCHAR(20);
ALTER TABLE "stations" ALTER COLUMN "email" SET DATA TYPE VARCHAR(254);
ALTER TABLE "stations" ALTER COLUMN "ice" SET DATA TYPE VARCHAR(15);
ALTER TABLE "stations" ALTER COLUMN "taxId" SET DATA TYPE VARCHAR(8);
ALTER TABLE "stations" ALTER COLUMN "rc" SET DATA TYPE VARCHAR(10);
ALTER TABLE "stations" ALTER COLUMN "patente" SET DATA TYPE VARCHAR(20);
ALTER TABLE "stations" ALTER COLUMN "stationCode" SET DATA TYPE VARCHAR(20);

-- AlterTable: FuelType
ALTER TABLE "fuel_types" ALTER COLUMN "code" SET DATA TYPE VARCHAR(20);
ALTER TABLE "fuel_types" ALTER COLUMN "name" SET DATA TYPE VARCHAR(50);

-- AlterTable: Tank
ALTER TABLE "tanks" ALTER COLUMN "reference" SET DATA TYPE VARCHAR(50);

-- AlterTable: Dispenser
ALTER TABLE "dispensers" ALTER COLUMN "reference" SET DATA TYPE VARCHAR(50);

-- AlterTable: Nozzle
ALTER TABLE "nozzles" ALTER COLUMN "reference" SET DATA TYPE VARCHAR(50);

-- AlterTable: PaymentMethod
ALTER TABLE "payment_methods" ALTER COLUMN "code" SET DATA TYPE VARCHAR(20);
ALTER TABLE "payment_methods" ALTER COLUMN "name" SET DATA TYPE VARCHAR(50);

-- AlterTable: SalePayment
ALTER TABLE "sale_payments" ALTER COLUMN "reference" SET DATA TYPE VARCHAR(100);

-- AlterTable: PaymentDetail
ALTER TABLE "payment_details" ALTER COLUMN "reference" SET DATA TYPE VARCHAR(100);

-- AlterTable: Supplier
ALTER TABLE "suppliers" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100);
ALTER TABLE "suppliers" ALTER COLUMN "contactName" SET DATA TYPE VARCHAR(100);
ALTER TABLE "suppliers" ALTER COLUMN "phone" SET DATA TYPE VARCHAR(20);
ALTER TABLE "suppliers" ALTER COLUMN "email" SET DATA TYPE VARCHAR(254);
ALTER TABLE "suppliers" ALTER COLUMN "address" SET DATA TYPE VARCHAR(255);
ALTER TABLE "suppliers" ALTER COLUMN "ice" SET DATA TYPE VARCHAR(15);
ALTER TABLE "suppliers" ALTER COLUMN "taxId" SET DATA TYPE VARCHAR(8);

-- AlterTable: Delivery
ALTER TABLE "deliveries" ALTER COLUMN "deliveryNoteNumber" SET DATA TYPE VARCHAR(50);

-- AlterTable: Client
ALTER TABLE "clients" ALTER COLUMN "companyName" SET DATA TYPE VARCHAR(150);
ALTER TABLE "clients" ALTER COLUMN "contactName" SET DATA TYPE VARCHAR(100);
ALTER TABLE "clients" ALTER COLUMN "ice" SET DATA TYPE VARCHAR(15);
ALTER TABLE "clients" ALTER COLUMN "taxId" SET DATA TYPE VARCHAR(8);
ALTER TABLE "clients" ALTER COLUMN "rc" SET DATA TYPE VARCHAR(10);
ALTER TABLE "clients" ALTER COLUMN "address" SET DATA TYPE VARCHAR(255);
ALTER TABLE "clients" ALTER COLUMN "phone" SET DATA TYPE VARCHAR(20);
ALTER TABLE "clients" ALTER COLUMN "email" SET DATA TYPE VARCHAR(254);

-- AlterTable: Invoice
ALTER TABLE "invoices" ALTER COLUMN "invoiceNumber" SET DATA TYPE VARCHAR(20);
ALTER TABLE "invoices" ALTER COLUMN "notes" SET DATA TYPE VARCHAR(2000);

-- AlterTable: InvoiceLine
ALTER TABLE "invoice_lines" ALTER COLUMN "description" SET DATA TYPE VARCHAR(500);

-- AlterTable: InvoicePayment
ALTER TABLE "invoice_payments" ALTER COLUMN "reference" SET DATA TYPE VARCHAR(100);
ALTER TABLE "invoice_payments" ALTER COLUMN "notes" SET DATA TYPE VARCHAR(500);

-- AlterTable: CreditNote
ALTER TABLE "credit_notes" ALTER COLUMN "creditNoteNumber" SET DATA TYPE VARCHAR(20);
ALTER TABLE "credit_notes" ALTER COLUMN "reason" SET DATA TYPE VARCHAR(500);

-- AlterTable: Alert
ALTER TABLE "alerts" ALTER COLUMN "title" SET DATA TYPE VARCHAR(200);
ALTER TABLE "alerts" ALTER COLUMN "message" SET DATA TYPE VARCHAR(2000);
ALTER TABLE "alerts" ALTER COLUMN "relatedEntityId" SET DATA TYPE VARCHAR(50);
ALTER TABLE "alerts" ALTER COLUMN "relatedEntityType" SET DATA TYPE VARCHAR(50);
